name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build_debug:
    name: Build debug
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Build debug
        run: ./gradlew assembleDebug