name: Deploy

on:
  push:
    tags:
      - '*.*.*'

jobs:
  create_release:
    name: Build and create release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up keystore
        run: openssl base64 -d <<< $KEYSTORE_BASE64 > keystore.jks
        env:
          KEYSTORE_BASE64: ${{secrets.KEYSTORE_BASE64}}

      - name: Build release artifacts
        run: |
          ./gradlew assembleRelease -Pmy_storepass=$STOREPASS -Pmy_keyalias=$KEYALIAS -Pmy_keypass=$KEYPASS
          ./gradlew bundleRelease -Pmy_storepass=$STOREPASS -Pmy_keyalias=$KEYALIAS -Pmy_keypass=$KEYPASS
        env:
          STOREPASS: ${{secrets.STOREPASS}}
          KEYALIAS: ${{secrets.KEYALIAS}}
          KEYPASS: ${{secrets.KEYPASS}}

      - name: Create GitHub pre-release
        run: gh release create ${{github.ref_name}} -t ${{github.ref_name}} -n "Generated release from GitHub Actions" -p
        env:
          GITHUB_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}

      - name: Upload artifacts
        run: |
          gh release upload ${{github.ref_name}} app/build/outputs/apk/release/*.apk
          gh release upload ${{github.ref_name}} app/build/outputs/bundle/release/*.aab
          gh release upload ${{github.ref_name}} app/build/outputs/mapping/release/mapping.txt
        env:
          GITHUB_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}